name       : libsoup
version    : 2.56.0
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/libsoup/2.56/libsoup-2.56.0.tar.xz : d8216b71de8247bc6f274ec054c08547b2e04369c1f8add713e9350c8ef81fe5
license    : LGPL-2.1
summary    : GNOME HTTP client/server library
builddeps  :
    - pkgconfig(sqlite3)
    - pkgconfig32(sqlite3)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(gnutls)
    - glib-networking
    - glib-networking-32bit
    - vala
component  : desktop.gnome.core
rundeps    :
    - glib-networking
    - 32bit :
        - glib-networking-32bit
emul32     : yes
description: |
    The libsoup is HTTP client/server library for GNOME. It uses GObject and the GLib main loop to integrate with GNOME applications and it also has asynchronous API for use in threaded applications.
setup      : |
    %configure --disable-static --prefix=/usr --disable-more-warnings --disable-tls-check
build      : |
    %make
install    : |
    %make_install
