name       : libsoup
version    : 2.60.3
release    : 17
source     :
    - https://download.gnome.org/sources/libsoup/2.60/libsoup-2.60.3.tar.xz : 1b0dc762f23abe4e0d29b77370e539fd35f31d8e8e0318d6ddccff395be68a22
license    : LGPL-2.1
component  : desktop.gnome.core
emul32     : yes
summary    : GNOME HTTP client/server library
description: |
    The libsoup is HTTP client/server library for GNOME. It uses GObject and the GLib main loop to integrate with GNOME applications and it also has asynchronous API for use in threaded applications.
builddeps  :
    - pkgconfig(sqlite3)
    - pkgconfig32(sqlite3)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(gnutls)
    - glib-networking
    - glib-networking-32bit
    - vala
rundeps    :
    - glib-networking
    - 32bit :
        - glib-networking-32bit
setup      : |
    %configure --disable-static --prefix=/usr --disable-more-warnings --disable-tls-check
build      : |
    %make
install    : |
    %make_install
