name        : libsoup
version     : 2.52.1
release     : 8
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libsoup/2.52/libsoup-2.52.1.tar.xz : 0e19bca047ad50b28e8ed7663840f9e45a94909148822ca44dcb3e8cafb5cc48
license     : GPL-3.0+
summary     : GNOME HTTP client/server library
builddeps   :
    - pkgconfig(sqlite3)
    - glib-networking
    - vala
description : |
    The libsoup is HTTP client/server library for GNOME. It uses GObject and the GLib main loop to integrate with GNOME applications and it also has asynchronous API for use in threaded applications.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
