name       : libsoup
version    : 2.68.1
release    : 25
source     :
    - https://download.gnome.org/sources/libsoup/2.68/libsoup-2.68.1.tar.xz : 7f0323e53b8e797baa972dfe25adf3cc6ceff06f0a26235b6c5c7b91403fbf8d
license    : LGPL-2.1-only
component  : desktop.gnome.core
emul32     : yes
summary    : GNOME HTTP client/server library
description: |
    The libsoup is HTTP client/server library for GNOME. It uses GObject and the GLib main loop to integrate with GNOME applications and it also has asynchronous API for use in threaded applications.
builddeps  :
    - pkgconfig32(gio-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(krb5)
    - pkgconfig32(libbrotlicommon)
    - pkgconfig32(libpsl)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(sqlite3)
    - glib-networking
    - glib-networking-32bit
    - gtk-doc
    - vala
rundeps    :
    - glib-networking
    - 32bit :
        - glib-networking-32bit
setup      : |
    %meson_configure -Dgtk_doc=true -Dtls_check=false
build      : |
    %ninja_build
install    : |
    %ninja_install
