name        : libsoup
version     : 2.50.0
release     : 7
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libsoup/2.50/libsoup-2.50.0.tar.xz : 1e01365ac4af3817187ea847f9d3588c27eee01fc519a5a7cb212bb78b0f667b
license     : GPL-3.0+
summary     : GNOME HTTP client/server library
builddeps   :
    - pkgconfig(sqlite3)
    - glib-networking
description : |
    The libsoup is HTTP client/server library for GNOME. It uses GObject and the GLib main loop to integrate with GNOME applications and it also has asynchronous API for use in threaded applications.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
